from .topic import Topic
from .degree import Degree
from .major import Major
from .department import Department
from .course_code import CourseCode
from .course import Course
from .faculty import Faculty
from .instructor import Instructor
from .advisor import Advisor
from .student import Student
from .course_section import CourseSection
from .scheduled_course_section import ScheduledCourseSection
